### ISSUE TITLE
Removing all products from cart..

### ISSUE THREAD

**Issue by omardhanish** [tosinonikute/carteasy#1]
how to remove all products from cart ?? Thanks ..

**Comment by tosinonikute** [comment]
Use
```Carteasy cs = new Carteasy(); 
cs.clearCart(Context context);```

**Comment by CreatorB** [comment]
mycart have > 1 item and i always getting force close when use cs.clearCart(mContext);

**Comment by tosinonikute** [comment]
Issue fixed, Use 
```implementation 'com.carteasy.v1.lib:carteasy:0.0.5'```

**Comment by jonwatt** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.savoir.ecommerce/com.savoir.ecommerce.activities.CheckoutActivity}: java.util.ConcurrentModificationException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601)
        at android.app.ActivityThread.access$800(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
     Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
        at java.util.HashMap$KeyIterator.next(HashMap.java:814)
        at com.carteasy.v1.lib.RemoveData.clearAllFromCart(RemoveData.java:194)
        at com.carteasy.v1.lib.Carteasy.clearCart(Carteasy.java:152)
        at com.savoir.ecommerce.activities.CheckoutActivity.init_cart(CheckoutActivity.java:159)
        at com.savoir.ecommerce.activities.CheckoutActivity.onCreate(CheckoutActivity.java:90)
        at android.app.Activity.performCreate(Activity.java:6100)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601) 
        at android.app.ActivityThread.access$800(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5637) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
