### ISSUE TITLE
Long cannot be cast to Integer

### ISSUE THREAD

**Issue by florianhirson** [tosinonikute/Carteasy#2]
I'm trying to add 1 to a quantity when the cart doesn't exist (so file not found exception) and concatenate the quantity when it does. Unfortunately I'm having a ClassCastException.
Here's my code : 

`                Carteasy cs = new Carteasy();
                cs.add(menuIdsList.get(position), "name", menu.getName());
                cs.add(menuIdsList.get(position), "description", menu.getDescription());
                cs.add(menuIdsList.get(position), "price", menu.getPrice());
                cs.add(menuIdsList.get(position), "picture", menu.getPicture());
                try {
                    int quantity = cs.getInteger(menuIdsList.get(position), "quantity", context.getApplicationContext());
                    ++quantity;
                    Log.d("Menu Adapter", "Quantity : " + quantity);
                    cs.update(menuIdsList.get(position), "quantity", quantity, context.getApplicationContext());
                } catch (Exception e) {
                    Log.w("Menu Adapter", e);
                    cs.add(menuIdsList.get(position), "quantity", 1);
                } finally {
                    cs.commit(context.getApplicationContext());
                    Log.d("Menu Adapter", "Changes to cart saved");
                }`

`java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
                                                                    at com.carteasy.v1.lib.Carteasy.getInteger(Carteasy.java:115)
                                                                    at stage.adapters.MenuAdapter$1.onClick(MenuAdapter.java:85)
                                                                    at android.view.View.performClick(View.java:6303)
                                                                    at android.view.View$PerformClick.run(View.java:24828)
                                                                    at android.os.Handler.handleCallback(Handler.java:789)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by tosinonikute** [comment]
This means the value you are getting is a Long value. Use ```Long value = cs.getLong(String id, String key, Context context);```
