### ISSUE TITLE
ClearCart Error

### ISSUE THREAD

**Issue by rademoh** [tosinonikute/Carteasy#4]
**This Error occurs when i call the clearCart Method:**
                                                   java.util.ConcurrentModificationException
                                                       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
                                                       at java.util.HashMap$KeyIterator.next(HashMap.java:885)
                                                       at com.carteasy.v1.lib.RemoveData.clearAllFromCart(RemoveData.java:194)
                                                       at com.carteasy.v1.lib.Carteasy.clearCart(Carteasy.java:152)

**Comment by rademoh** [comment]
when more than one item is added to the cart

**Comment by hinachauhan09** [comment]
Even I has same issue.
 E/AndroidRuntime: FATAL EXCEPTION: 
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
        at com.carteasy.v1.lib.RemoveData.clearAllFromCart(RemoveData.java:194)
        at com.carteasy.v1.lib.Carteasy.clearCart(Carteasy.java:152)
        at com.tantoo.scthreads.helper.CartHashMap.clearCart(CartHashMap.java:213)
        at com.tantoo.scthreads.activity.CartActivity$4.onResponse(CartActivity.java:158)
        at com.androidnetworking.common.ANRequest.deliverSuccessResponse(ANRequest.java:727)
        at com.androidnetworking.common.ANRequest.access$6500(ANRequest.java:80)
        at com.androidnetworking.common.ANRequest$6.run(ANRequest.java:709)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by tosinonikute** [comment]
Fixed. Use implementation 'com.carteasy.v1.lib:carteasy:0.0.5'

**Comment by hinachauhan09** [comment]
Thanks.!! It works like Charm.
